export interface IngredientAliasMappingEntry {
  alias: string;
  ndbNumber: string | null;
  notes?: string;
}

const NO_RAW_FORM = 'Forme crue/brute absente de CORGIS (dataset orienté aliments consommés) ; valeur basée sur la forme cuite la plus neutre disponible.';
const VARIETY_NOT_DISTINGUISHED = 'CORGIS ne distingue pas cette variété/coupe précise ; valeur sur l\'entrée générique la plus proche.';
const NOT_IN_CORGIS = 'Aucune entrée correspondante dans CORGIS (épice/ingrédient brut absent de ce dataset de consommation) — à traiter dans un futur lexique dédié.';
const COMPOSITE_NO_MATCH = 'Produit composite/transformé sans équivalent fiable à 1 entrée dans CORGIS — nécessite une décomposition en ingrédients de base (ticket futur).';

export const INGREDIENT_ALIAS_MAPPING: IngredientAliasMappingEntry[] = [
  { alias: 'ail', ndbNumber: '75111500' },
  { alias: 'algues wakame', ndbNumber: '75127500', notes: 'Espèce wakame non distinguée ; valeur sur algue générique (Seaweed, raw).' },
  { alias: 'amandes effilees', ndbNumber: '42100100', notes: VARIETY_NOT_DISTINGUISHED },
  { alias: 'aneth frais', ndbNumber: null, notes: NOT_IN_CORGIS },
  { alias: 'aubergine', ndbNumber: '75111200' },
  { alias: 'banane', ndbNumber: '63107010' },
  { alias: 'basilic frais', ndbNumber: '75109400' },
  { alias: 'beurre', ndbNumber: '81100500' },
  { alias: 'blanc de poulet', ndbNumber: '24122131', notes: NO_RAW_FORM + ' Sans peau.' },
  { alias: 'boeuf a braiser', ndbNumber: '21410110', notes: NO_RAW_FORM + ' Coupe générique "stew meat".' },
  { alias: 'bouillon de legumes', ndbNumber: '75657000' },
  { alias: 'bouquet garni', ndbNumber: null, notes: NOT_IN_CORGIS + ' (bouquet d\'herbes composite : thym, laurier, persil).' },
  { alias: 'brocoli', ndbNumber: '72201100' },
  { alias: 'cacahuetes concassees', ndbNumber: '42111040', notes: VARIETY_NOT_DISTINGUISHED },
  { alias: 'cannelle', ndbNumber: null, notes: NOT_IN_CORGIS },
  { alias: 'carotte', ndbNumber: '73101010' },
  { alias: 'champignons de paris', ndbNumber: '75115000' },
  { alias: 'chapelure', ndbNumber: '99995000', notes: 'Correspond à "Breading or batter as ingredient in food".' },
  { alias: 'cheddar', ndbNumber: '14104100' },
  { alias: 'citron', ndbNumber: '61113010' },
  { alias: 'citron vert', ndbNumber: '61116010' },
  { alias: 'concombre', ndbNumber: '75111000' },
  { alias: 'courgette', ndbNumber: '75128010', notes: 'Correspond à "Summer squash, green, raw".' },
  { alias: 'creme fraiche', ndbNumber: '12130100', notes: 'Pas d\'entrée "crème fraîche" française ; valeur sur "Cream, heavy" (profil lipidique proche).' },
  { alias: 'crevettes decortiquees', ndbNumber: '26319130', notes: NO_RAW_FORM },
  { alias: 'cumin moulu', ndbNumber: null, notes: NOT_IN_CORGIS },
  { alias: 'curcuma moulu', ndbNumber: null, notes: NOT_IN_CORGIS },
  { alias: 'curry en poudre', ndbNumber: null, notes: NOT_IN_CORGIS },
  { alias: 'eau', ndbNumber: '94000100' },
  { alias: 'epinards frais', ndbNumber: '72125100' },
  { alias: 'farine de ble', ndbNumber: null, notes: NOT_IN_CORGIS },
  { alias: 'feta', ndbNumber: '14104400' },
  { alias: 'filet de cabillaud', ndbNumber: '26109160', notes: NO_RAW_FORM + ' "Cod, steamed or poached".' },
  { alias: 'flocons d\'avoine', ndbNumber: '57602100' },
  { alias: 'fromage rape', ndbNumber: '14010000', notes: 'Fromage générique non spécifié dans la recette ; "Cheese, NFS".' },
  { alias: 'fruits rouges', ndbNumber: null, notes: COMPOSITE_NO_MATCH + ' (mélange de baies : fraises, myrtilles, framboises...).' },
  { alias: 'gingembre frais', ndbNumber: null, notes: NOT_IN_CORGIS + ' (seule forme présente : gingembre confit/mariné).' },
  { alias: 'graines de chia', ndbNumber: '43108010' },
  { alias: 'gruyere rape', ndbNumber: '14105200' },
  { alias: 'haricots rouges cuits', ndbNumber: '41106020' },
  { alias: 'herbes de provence', ndbNumber: null, notes: NOT_IN_CORGIS + ' (mélange d\'herbes composite).' },
  { alias: 'huile d\'olive', ndbNumber: '82104000' },
  { alias: 'huile de coco', ndbNumber: '82101500' },
  { alias: 'huile de sesame', ndbNumber: '82107000' },
  { alias: 'lait', ndbNumber: '11111000' },
  { alias: 'lait d\'amande', ndbNumber: '11350020', notes: 'Variante non sucrée.' },
  { alias: 'lait de coco', ndbNumber: '11370000' },
  { alias: 'lardons', ndbNumber: '22600100', notes: NO_RAW_FORM },
  { alias: 'lentilles corail', ndbNumber: '41305000', notes: VARIETY_NOT_DISTINGUISHED },
  { alias: 'lentilles vertes', ndbNumber: '41305000', notes: VARIETY_NOT_DISTINGUISHED },
  { alias: 'levure chimique', ndbNumber: null, notes: NOT_IN_CORGIS },
  { alias: 'mais', ndbNumber: '75109600' },
  { alias: 'miel', ndbNumber: '91302010' },
  { alias: 'mozzarella', ndbNumber: '14107010' },
  { alias: 'noix de cajou', ndbNumber: '42104000' },
  { alias: 'nouilles de riz', ndbNumber: '56117090' },
  { alias: 'oeuf', ndbNumber: '31101010' },
  { alias: 'oignon', ndbNumber: '75117020' },
  { alias: 'oignon nouveau', ndbNumber: '75117010' },
  { alias: 'oignon rouge', ndbNumber: '75117020', notes: VARIETY_NOT_DISTINGUISHED },
  { alias: 'olives noires', ndbNumber: '75510020' },
  { alias: 'origan sec', ndbNumber: null, notes: NOT_IN_CORGIS },
  { alias: 'pain a burger', ndbNumber: '51154100' },
  { alias: 'paprika fume', ndbNumber: null, notes: NOT_IN_CORGIS },
  { alias: 'parmesan', ndbNumber: '14108010' },
  { alias: 'patate douce', ndbNumber: '73405010', notes: NO_RAW_FORM + ' Bouillie.' },
  { alias: 'pate a pizza', ndbNumber: null, notes: COMPOSITE_NO_MATCH + ' (seules les pizzas finies existent, composition trop différente de la pâte crue).' },
  { alias: 'pate brisee', ndbNumber: '53391000', notes: 'Correspond à "Pie shell" (pâte à tarte cuite).' },
  { alias: 'pate de curry rouge', ndbNumber: null, notes: COMPOSITE_NO_MATCH + ' (seule "Curry sauce" existe, déjà diluée/différente d\'une pâte concentrée).' },
  { alias: 'pate miso', ndbNumber: '41420110' },
  { alias: 'pave de saumon', ndbNumber: '26137100' },
  { alias: 'persil frais', ndbNumber: '75119000' },
  { alias: 'petits pois', ndbNumber: '75120000' },
  { alias: 'piment doux', ndbNumber: null, notes: NOT_IN_CORGIS },
  { alias: 'piment en poudre', ndbNumber: null, notes: NOT_IN_CORGIS },
  { alias: 'poireau', ndbNumber: '75112500' },
  { alias: 'pois chiches cuits', ndbNumber: '41302020' },
  { alias: 'pois chiches secs trempes', ndbNumber: '41302020', notes: 'État "trempé puis cuit" non distingué ; pois chiches cuits génériques.' },
  { alias: 'poivre noir', ndbNumber: null, notes: NOT_IN_CORGIS },
  { alias: 'poivron', ndbNumber: '75122200', notes: 'Couleur non précisée dans la recette ; défaut sur poivron rouge.' },
  { alias: 'poivron rouge', ndbNumber: '75122200' },
  { alias: 'poivron vert', ndbNumber: '75122100' },
  { alias: 'pomme', ndbNumber: '63101000' },
  { alias: 'pomme de terre', ndbNumber: '71000100', notes: NO_RAW_FORM },
  { alias: 'poulet entier', ndbNumber: '24102010', notes: NO_RAW_FORM + ' Rôti, peau comprise.' },
  { alias: 'pousses de soja', ndbNumber: '75101000' },
  { alias: 'quinoa', ndbNumber: '56204005', notes: 'Cuit, sans matière grasse ajoutée.' },
  { alias: 'riz arborio', ndbNumber: '56205008', notes: VARIETY_NOT_DISTINGUISHED + ' Riz blanc cuit générique.' },
  { alias: 'riz basmati', ndbNumber: '56205008', notes: VARIETY_NOT_DISTINGUISHED + ' Riz blanc cuit générique.' },
  { alias: 'riz cuit refroidi', ndbNumber: '56205008', notes: 'Refroidissement non distingué ; riz blanc cuit générique.' },
  { alias: 'salade verte', ndbNumber: '75113000' },
  { alias: 'sauce soja', ndbNumber: '41420300' },
  { alias: 'sauce tomate', ndbNumber: '89901050' },
  { alias: 'sauce yaourt', ndbNumber: '83115000', notes: 'Correspond à "Yogurt dressing".' },
  { alias: 'spaghetti', ndbNumber: '56130000', notes: 'Correspond à "Pasta, cooked" (forme spécifique spaghetti non distinguée).' },
  { alias: 'sucre', ndbNumber: '91101000' },
  { alias: 'tahini', ndbNumber: '43103300' },
  { alias: 'thym', ndbNumber: null, notes: NOT_IN_CORGIS },
  { alias: 'tofu ferme', ndbNumber: '41420010', notes: 'CORGIS ne distingue pas ferme/soyeux ; tofu nature générique.' },
  { alias: 'tofu soyeux', ndbNumber: '41420010', notes: 'CORGIS ne distingue pas ferme/soyeux ; tofu nature générique.' },
  { alias: 'tomate', ndbNumber: '74101000' },
  { alias: 'tomate concassee', ndbNumber: '74201003', notes: 'Correspond à "Tomatoes, canned, cooked".' },
  { alias: 'tortilla de ble', ndbNumber: '52215200' },
  { alias: 'vin blanc', ndbNumber: '93401020' },
  { alias: 'vin rouge', ndbNumber: '93401010' },
  { alias: 'vinaigre de xeres', ndbNumber: '64401000', notes: 'Variante "xérès" non distinguée ; vinaigre générique.' },
  { alias: 'yaourt grec', ndbNumber: '11411400' },
];
