import { RecipeInput } from '@my-food-recipes/contracts';

// All recipes are stored for 1 person (`servings: 1`). Ingredient quantities
// were rescaled down from the original multi-portion versions using culinary
// judgment rather than mechanical division: discrete proteins (eggs, fillets)
// round to a usable whole/half unit instead of an unusable fraction, while
// produce and seasonings keep fractional quantities that are normal in a
// recipe (e.g. "0.25 oignon").
export const RECIPES_SEED: RecipeInput[] = [
  {
    id: 'salade-grecque',
    name: 'Salade grecque',
    servings: 1,
    dietTags: ['vegetarien'],
    allergens: ['lactose'],
    requiredAppliances: [],
    prepTimeMinutes: 15,
    cookTimeMinutes: 0,
    nutrition: { calories: 70, protein: 2, carbs: 3, fat: 6 },
    ingredients: [
      { name: 'tomate', quantity: 1, unit: 'piece', category: 'legumes' },
      { name: 'concombre', quantity: 0.5, unit: 'piece', category: 'legumes' },
      { name: 'poivron vert', quantity: 0.25, unit: 'piece', category: 'legumes' },
      { name: 'oignon rouge', quantity: 0.25, unit: 'piece', category: 'legumes' },
      { name: 'feta', quantity: 50, unit: 'g', category: 'produits_laitiers' },
      { name: 'olives noires', quantity: 25, unit: 'g', category: 'epicerie' },
      { name: "huile d'olive", quantity: 1, unit: 'cas', category: 'matieres_grasses' },
      { name: 'origan sec', quantity: 1, unit: 'pincee', category: 'epices_condiments' },
    ],
    steps: [
      'Couper la tomate, le concombre, le poivron et l\'oignon en morceaux.',
      'Mélanger les légumes dans un saladier.',
      'Ajouter la feta émiettée et les olives.',
      'Arroser d\'huile d\'olive et saupoudrer d\'origan avant de servir.',
    ],
  },
  {
    id: 'houmous-maison',
    name: 'Houmous maison',
    servings: 1,
    dietTags: ['vegan', 'sans_gluten'],
    allergens: ['sesame'],
    requiredAppliances: ['robot'],
    prepTimeMinutes: 10,
    cookTimeMinutes: 0,
    nutrition: { calories: 53, protein: 2, carbs: 5, fat: 3 },
    ingredients: [
      { name: 'pois chiches cuits', quantity: 100, unit: 'g', category: 'legumineuses' },
      { name: 'tahini', quantity: 1, unit: 'cas', category: 'epicerie' },
      { name: 'citron', quantity: 0.25, unit: 'piece', category: 'fruits' },
      { name: 'ail', quantity: 0.25, unit: 'gousse', category: 'epices_condiments' },
      { name: "huile d'olive", quantity: 1, unit: 'cas', category: 'matieres_grasses' },
      { name: 'cumin moulu', quantity: 1, unit: 'pincee', category: 'epices_condiments' },
    ],
    steps: [
      'Égoutter les pois chiches et les placer dans le robot.',
      "Ajouter le tahini, le jus de citron, l'ail et le cumin.",
      "Mixer en filet d'huile d'olive jusqu'à obtenir une texture lisse.",
      'Rectifier l\'assaisonnement et servir frais.',
    ],
  },
  {
    id: 'curry-pois-chiches',
    name: 'Curry de pois chiches',
    servings: 1,
    dietTags: ['vegan', 'sans_gluten'],
    allergens: [],
    requiredAppliances: ['plaque_cuisson'],
    prepTimeMinutes: 10,
    cookTimeMinutes: 20,
    nutrition: { calories: 80, protein: 3, carbs: 10, fat: 3.5 },
    ingredients: [
      { name: 'pois chiches cuits', quantity: 125, unit: 'g', category: 'legumineuses' },
      { name: 'lait de coco', quantity: 100, unit: 'ml', category: 'epicerie' },
      { name: 'oignon', quantity: 0.25, unit: 'piece', category: 'legumes' },
      { name: 'tomate concassee', quantity: 100, unit: 'g', category: 'legumes' },
      { name: 'curry en poudre', quantity: 0.5, unit: 'cas', category: 'epices_condiments' },
      { name: 'ail', quantity: 0.5, unit: 'gousse', category: 'epices_condiments' },
      { name: 'riz basmati', quantity: 75, unit: 'g', category: 'feculents' },
    ],
    steps: [
      "Faire revenir l'oignon et l'ail émincés dans une poêle.",
      'Ajouter le curry en poudre puis la tomate concassée.',
      'Incorporer les pois chiches et le lait de coco, laisser mijoter 15 minutes.',
      'Cuire le riz basmati à part et servir le curry dessus.',
    ],
  },
  {
    id: 'ratatouille',
    name: 'Ratatouille provençale',
    servings: 1,
    dietTags: ['vegan', 'sans_gluten'],
    allergens: [],
    requiredAppliances: ['plaque_cuisson'],
    prepTimeMinutes: 10,
    cookTimeMinutes: 30,
    nutrition: { calories: 45, protein: 1, carbs: 5, fat: 2 },
    ingredients: [
      { name: 'aubergine', quantity: 0.5, unit: 'piece', category: 'legumes' },
      { name: 'courgette', quantity: 0.5, unit: 'piece', category: 'legumes' },
      { name: 'poivron rouge', quantity: 0.25, unit: 'piece', category: 'legumes' },
      { name: 'tomate', quantity: 1, unit: 'piece', category: 'legumes' },
      { name: 'oignon', quantity: 0.25, unit: 'piece', category: 'legumes' },
      { name: "huile d'olive", quantity: 1, unit: 'cas', category: 'matieres_grasses' },
      { name: 'herbes de provence', quantity: 1, unit: 'cac', category: 'epices_condiments' },
    ],
    steps: [
      'Couper tous les légumes en dés réguliers.',
      "Faire revenir l'oignon dans l'huile d'olive puis ajouter les autres légumes.",
      'Assaisonner avec les herbes de provence, saler et poivrer.',
      'Laisser mijoter à couvert 30 minutes en remuant régulièrement.',
    ],
  },
  {
    id: 'risotto-champignons',
    name: 'Risotto aux champignons',
    servings: 1,
    dietTags: ['vegetarien', 'sans_gluten'],
    allergens: ['lactose'],
    requiredAppliances: ['plaque_cuisson'],
    prepTimeMinutes: 15,
    cookTimeMinutes: 20,
    nutrition: { calories: 103, protein: 2.25, carbs: 14.5, fat: 3.5 },
    ingredients: [
      { name: 'riz arborio', quantity: 80, unit: 'g', category: 'feculents' },
      { name: 'champignons de paris', quantity: 75, unit: 'g', category: 'legumes' },
      { name: 'bouillon de legumes', quantity: 250, unit: 'ml', category: 'epicerie' },
      { name: 'oignon', quantity: 0.25, unit: 'piece', category: 'legumes' },
      { name: 'parmesan', quantity: 20, unit: 'g', category: 'produits_laitiers' },
      { name: 'beurre', quantity: 8, unit: 'g', category: 'produits_laitiers' },
      { name: 'vin blanc', quantity: 25, unit: 'ml', category: 'boissons' },
    ],
    steps: [
      "Faire suer l'oignon émincé dans le beurre puis ajouter le riz.",
      'Verser le vin blanc et laisser réduire.',
      'Ajouter le bouillon chaud louche par louche en remuant.',
      'Incorporer les champignons poêlés et le parmesan en fin de cuisson.',
    ],
  },
  {
    id: 'pates-carbonara',
    name: 'Pâtes carbonara',
    servings: 1,
    dietTags: ['omnivore'],
    allergens: ['gluten', 'lactose', 'oeufs'],
    requiredAppliances: ['plaque_cuisson'],
    prepTimeMinutes: 10,
    cookTimeMinutes: 15,
    nutrition: { calories: 140, protein: 6, carbs: 15, fat: 6 },
    ingredients: [
      { name: 'spaghetti', quantity: 100, unit: 'g', category: 'feculents' },
      { name: 'lardons', quantity: 50, unit: 'g', category: 'viande_poisson' },
      { name: 'oeuf', quantity: 1, unit: 'piece', category: 'produits_laitiers' },
      { name: 'parmesan', quantity: 20, unit: 'g', category: 'produits_laitiers' },
      { name: 'poivre noir', quantity: 1, unit: 'pincee', category: 'epices_condiments' },
    ],
    steps: [
      'Cuire les spaghetti dans l\'eau bouillante salée.',
      'Faire revenir les lardons à la poêle.',
      'Battre l\'oeuf avec le parmesan et le poivre.',
      'Mélanger les pâtes égouttées avec les lardons puis hors du feu avec l\'appareil aux oeufs.',
    ],
  },
  {
    id: 'poulet-roti-legumes',
    name: 'Poulet rôti aux légumes',
    servings: 1,
    dietTags: ['omnivore', 'sans_gluten'],
    allergens: [],
    requiredAppliances: ['four'],
    prepTimeMinutes: 15,
    cookTimeMinutes: 30,
    nutrition: { calories: 120, protein: 10, carbs: 6, fat: 6 },
    ingredients: [
      { name: 'blanc de poulet', quantity: 150, unit: 'g', category: 'viande_poisson' },
      { name: 'pomme de terre', quantity: 2, unit: 'piece', category: 'feculents' },
      { name: 'carotte', quantity: 1, unit: 'piece', category: 'legumes' },
      { name: 'oignon', quantity: 0.5, unit: 'piece', category: 'legumes' },
      { name: "huile d'olive", quantity: 1, unit: 'cas', category: 'matieres_grasses' },
      { name: 'thym', quantity: 1, unit: 'pincee', category: 'epices_condiments' },
    ],
    steps: [
      'Préchauffer le four à 200°C.',
      'Couper les légumes en gros morceaux et les disposer dans un plat.',
      "Badigeonner le blanc de poulet d'huile d'olive et de thym, puis le poser sur les légumes.",
      'Enfourner 30 minutes en arrosant régulièrement de jus de cuisson.',
    ],
  },
  {
    id: 'saumon-papillote',
    name: 'Saumon en papillote',
    servings: 1,
    dietTags: ['omnivore', 'pescatarien', 'sans_gluten'],
    allergens: ['poisson'],
    requiredAppliances: ['four'],
    prepTimeMinutes: 10,
    cookTimeMinutes: 20,
    nutrition: { calories: 85, protein: 8, carbs: 1.5, fat: 5 },
    ingredients: [
      { name: 'pave de saumon', quantity: 1, unit: 'piece', category: 'viande_poisson' },
      { name: 'citron', quantity: 0.25, unit: 'piece', category: 'fruits' },
      { name: 'courgette', quantity: 0.5, unit: 'piece', category: 'legumes' },
      { name: 'aneth frais', quantity: 1, unit: 'brin', category: 'epices_condiments' },
      { name: "huile d'olive", quantity: 0.5, unit: 'cas', category: 'matieres_grasses' },
    ],
    steps: [
      'Préchauffer le four à 180°C.',
      'Couper la courgette en fines rondelles et les disposer au centre d\'une feuille de papier sulfurisé.',
      'Déposer le pavé de saumon sur le lit de légumes.',
      "Arroser d'huile d'olive, de jus de citron et d'aneth, fermer la papillote et enfourner 20 minutes.",
    ],
  },
  {
    id: 'quiche-legumes',
    name: 'Quiche aux légumes',
    servings: 1,
    dietTags: ['vegetarien'],
    allergens: ['gluten', 'lactose', 'oeufs'],
    requiredAppliances: ['four'],
    prepTimeMinutes: 15,
    cookTimeMinutes: 35,
    nutrition: { calories: 53, protein: 2, carbs: 4, fat: 3 },
    ingredients: [
      { name: 'pate brisee', quantity: 40, unit: 'g', category: 'epicerie' },
      { name: 'courgette', quantity: 0.33, unit: 'piece', category: 'legumes' },
      { name: 'poireau', quantity: 0.25, unit: 'piece', category: 'legumes' },
      { name: 'oeuf', quantity: 1, unit: 'piece', category: 'produits_laitiers' },
      { name: 'creme fraiche', quantity: 33, unit: 'ml', category: 'produits_laitiers' },
      { name: 'gruyere rape', quantity: 17, unit: 'g', category: 'produits_laitiers' },
    ],
    steps: [
      'Préchauffer le four à 180°C et étaler la pâte dans un petit moule.',
      'Faire revenir le poireau et la courgette émincés.',
      "Battre l'oeuf avec la crème fraîche et le fromage rapé.",
      "Répartir les légumes sur la pâte, verser l'appareil et enfourner 35 minutes.",
    ],
  },
  {
    id: 'soupe-lentilles',
    name: 'Soupe de lentilles',
    servings: 1,
    dietTags: ['vegan', 'sans_gluten'],
    allergens: [],
    requiredAppliances: ['plaque_cuisson', 'blender'],
    prepTimeMinutes: 10,
    cookTimeMinutes: 25,
    nutrition: { calories: 63, protein: 3, carbs: 9.5, fat: 1 },
    ingredients: [
      { name: 'lentilles vertes', quantity: 75, unit: 'g', category: 'legumineuses' },
      { name: 'carotte', quantity: 0.5, unit: 'piece', category: 'legumes' },
      { name: 'oignon', quantity: 0.25, unit: 'piece', category: 'legumes' },
      { name: 'bouillon de legumes', quantity: 250, unit: 'ml', category: 'epicerie' },
      { name: 'cumin moulu', quantity: 1, unit: 'pincee', category: 'epices_condiments' },
    ],
    steps: [
      'Faire revenir l\'oignon et la carotte émincés.',
      'Ajouter les lentilles rincées et le bouillon.',
      'Laisser mijoter 25 minutes jusqu\'à ce que les lentilles soient tendres.',
      'Mixer tout ou partie selon la texture désirée et assaisonner.',
    ],
  },
  {
    id: 'tofu-saute-legumes',
    name: 'Tofu sauté aux légumes',
    servings: 1,
    dietTags: ['vegan', 'sans_gluten'],
    allergens: ['soja'],
    requiredAppliances: ['plaque_cuisson'],
    prepTimeMinutes: 10,
    cookTimeMinutes: 15,
    nutrition: { calories: 73, protein: 4.5, carbs: 4.5, fat: 4 },
    ingredients: [
      { name: 'tofu ferme', quantity: 100, unit: 'g', category: 'legumineuses' },
      { name: 'brocoli', quantity: 0.25, unit: 'piece', category: 'legumes' },
      { name: 'carotte', quantity: 0.5, unit: 'piece', category: 'legumes' },
      { name: 'sauce soja', quantity: 1, unit: 'cas', category: 'epicerie' },
      { name: 'gingembre frais', quantity: 1, unit: 'morceau', category: 'epices_condiments' },
      { name: 'huile de sesame', quantity: 0.5, unit: 'cas', category: 'matieres_grasses' },
    ],
    steps: [
      'Couper le tofu en cubes et le faire dorer dans l\'huile de sésame.',
      'Réserver le tofu et faire sauter le brocoli et la carotte coupés en bâtonnets.',
      'Ajouter le gingembre haché et la sauce soja.',
      'Remettre le tofu, mélanger et servir chaud.',
    ],
  },
  {
    id: 'tarte-aux-pommes',
    name: 'Tarte aux pommes',
    servings: 1,
    dietTags: ['vegetarien'],
    allergens: ['gluten', 'lactose', 'oeufs'],
    requiredAppliances: ['four'],
    prepTimeMinutes: 20,
    cookTimeMinutes: 35,
    nutrition: { calories: 35, protein: 0.5, carbs: 5, fat: 1 },
    ingredients: [
      { name: 'pate brisee', quantity: 29, unit: 'g', category: 'epicerie' },
      { name: 'pomme', quantity: 0.75, unit: 'piece', category: 'fruits' },
      { name: 'sucre', quantity: 10, unit: 'g', category: 'epicerie' },
      { name: 'beurre', quantity: 3, unit: 'g', category: 'produits_laitiers' },
      { name: 'oeuf', quantity: 1, unit: 'cas', category: 'produits_laitiers' },
      { name: 'cannelle', quantity: 1, unit: 'pincee', category: 'epices_condiments' },
    ],
    steps: [
      'Préchauffer le four à 180°C et étaler la pâte dans un petit moule.',
      'Éplucher et couper la pomme en fines lamelles.',
      'Disposer la pomme sur la pâte, saupoudrer de sucre et de cannelle.',
      "Badigeonner les bords d'oeuf battu et enfourner 35 minutes.",
    ],
  },
  {
    id: 'smoothie-banane-epinard',
    name: 'Smoothie banane-épinard',
    servings: 1,
    dietTags: ['vegan', 'sans_gluten'],
    allergens: [],
    requiredAppliances: ['blender'],
    prepTimeMinutes: 5,
    cookTimeMinutes: 0,
    nutrition: { calories: 80, protein: 1.5, carbs: 17.5, fat: 0.5 },
    ingredients: [
      { name: 'banane', quantity: 1, unit: 'piece', category: 'fruits' },
      { name: 'epinards frais', quantity: 25, unit: 'g', category: 'legumes' },
      { name: "lait d'amande", quantity: 150, unit: 'ml', category: 'boissons' },
      { name: 'graines de chia', quantity: 0.5, unit: 'cas', category: 'epicerie' },
    ],
    steps: [
      'Placer tous les ingrédients dans le blender.',
      "Mixer jusqu'à obtenir une texture lisse.",
      'Servir immédiatement bien frais.',
    ],
  },
  {
    id: 'gaspacho',
    name: 'Gaspacho andalou',
    servings: 1,
    dietTags: ['vegan', 'sans_gluten'],
    allergens: [],
    requiredAppliances: ['blender'],
    prepTimeMinutes: 15,
    cookTimeMinutes: 0,
    nutrition: { calories: 30, protein: 0.5, carbs: 3, fat: 2 },
    ingredients: [
      { name: 'tomate', quantity: 1.5, unit: 'piece', category: 'legumes' },
      { name: 'concombre', quantity: 0.25, unit: 'piece', category: 'legumes' },
      { name: 'poivron rouge', quantity: 0.25, unit: 'piece', category: 'legumes' },
      { name: 'ail', quantity: 0.25, unit: 'gousse', category: 'epices_condiments' },
      { name: "huile d'olive", quantity: 1, unit: 'cas', category: 'matieres_grasses' },
      { name: 'vinaigre de xeres', quantity: 1, unit: 'cac', category: 'epicerie' },
    ],
    steps: [
      'Couper grossièrement tous les légumes.',
      "Mixer le tout avec l'ail, l'huile d'olive et le vinaigre.",
      'Filtrer si désiré et réfrigérer au moins 2 heures avant de servir.',
    ],
  },
  {
    id: 'falafels-au-four',
    name: 'Falafels au four',
    servings: 1,
    dietTags: ['vegan'],
    allergens: ['sesame'],
    requiredAppliances: ['robot', 'four'],
    prepTimeMinutes: 15,
    cookTimeMinutes: 25,
    nutrition: { calories: 65, protein: 2.5, carbs: 7.5, fat: 2.5 },
    ingredients: [
      { name: 'pois chiches secs trempes', quantity: 75, unit: 'g', category: 'legumineuses' },
      { name: 'persil frais', quantity: 10, unit: 'g', category: 'legumes' },
      { name: 'oignon', quantity: 0.25, unit: 'piece', category: 'legumes' },
      { name: 'ail', quantity: 0.5, unit: 'gousse', category: 'epices_condiments' },
      { name: 'cumin moulu', quantity: 1, unit: 'pincee', category: 'epices_condiments' },
      { name: 'tahini', quantity: 0.5, unit: 'cas', category: 'epicerie' },
    ],
    steps: [
      "Mixer les pois chiches égouttés avec le persil, l'oignon et l'ail.",
      'Ajouter le cumin et façonner des petites boulettes.',
      'Disposer sur une plaque huilée et enfourner 25 minutes à 200°C en retournant à mi-cuisson.',
      'Servir avec une sauce au tahini.',
    ],
  },
  {
    id: 'curry-legumes-coco',
    name: 'Curry de légumes au lait de coco',
    servings: 1,
    dietTags: ['vegan', 'sans_gluten'],
    allergens: [],
    requiredAppliances: ['plaque_cuisson'],
    prepTimeMinutes: 10,
    cookTimeMinutes: 20,
    nutrition: { calories: 75, protein: 1.5, carbs: 7.5, fat: 4.5 },
    ingredients: [
      { name: 'patate douce', quantity: 0.5, unit: 'piece', category: 'feculents' },
      { name: 'courgette', quantity: 0.5, unit: 'piece', category: 'legumes' },
      { name: 'poivron rouge', quantity: 0.25, unit: 'piece', category: 'legumes' },
      { name: 'lait de coco', quantity: 100, unit: 'ml', category: 'epicerie' },
      { name: 'pate de curry rouge', quantity: 0.5, unit: 'cas', category: 'epices_condiments' },
      { name: 'riz basmati', quantity: 75, unit: 'g', category: 'feculents' },
    ],
    steps: [
      'Couper les légumes en cubes.',
      'Faire revenir la pâte de curry puis ajouter les légumes.',
      'Verser le lait de coco et laisser mijoter 20 minutes.',
      'Servir avec du riz basmati cuit à part.',
    ],
  },
  {
    id: 'omelette-legumes',
    name: 'Omelette aux légumes',
    servings: 1,
    dietTags: ['vegetarien', 'sans_gluten'],
    allergens: ['oeufs'],
    requiredAppliances: ['plaque_cuisson'],
    prepTimeMinutes: 7,
    cookTimeMinutes: 8,
    nutrition: { calories: 140, protein: 9, carbs: 4, fat: 10 },
    ingredients: [
      { name: 'oeuf', quantity: 3, unit: 'piece', category: 'produits_laitiers' },
      { name: 'poivron', quantity: 0.5, unit: 'piece', category: 'legumes' },
      { name: 'champignons de paris', quantity: 50, unit: 'g', category: 'legumes' },
      { name: 'fromage rape', quantity: 25, unit: 'g', category: 'produits_laitiers' },
      { name: "huile d'olive", quantity: 0.5, unit: 'cas', category: 'matieres_grasses' },
    ],
    steps: [
      'Battre les oeufs et assaisonner.',
      "Faire revenir le poivron et les champignons émincés dans l'huile.",
      'Verser les oeufs battus sur les légumes et laisser cuire à feu doux.',
      "Ajouter le fromage rapé avant de plier l'omelette et servir.",
    ],
  },
  {
    id: 'tofu-pad-thai',
    name: 'Pad thaï au tofu',
    servings: 1,
    dietTags: ['vegan'],
    allergens: ['soja', 'fruits_a_coque'],
    requiredAppliances: ['plaque_cuisson'],
    prepTimeMinutes: 15,
    cookTimeMinutes: 15,
    nutrition: { calories: 105, protein: 4, carbs: 13, fat: 4 },
    ingredients: [
      { name: 'nouilles de riz', quantity: 75, unit: 'g', category: 'feculents' },
      { name: 'tofu ferme', quantity: 75, unit: 'g', category: 'legumineuses' },
      { name: 'pousses de soja', quantity: 38, unit: 'g', category: 'legumes' },
      { name: 'carotte', quantity: 0.25, unit: 'piece', category: 'legumes' },
      { name: 'cacahuetes concassees', quantity: 13, unit: 'g', category: 'epicerie' },
      { name: 'sauce soja', quantity: 1, unit: 'cas', category: 'epicerie' },
      { name: 'citron vert', quantity: 0.25, unit: 'piece', category: 'fruits' },
    ],
    steps: [
      'Faire tremper les nouilles de riz selon les instructions du paquet.',
      'Faire dorer le tofu coupé en dés à la poêle.',
      'Ajouter la carotte en julienne et les pousses de soja, sauter 3 minutes.',
      'Incorporer les nouilles, la sauce soja, le jus de citron vert et les cacahuètes.',
    ],
  },
  {
    id: 'bowl-quinoa-legumes-rotis',
    name: 'Bowl de quinoa et légumes rôtis',
    servings: 1,
    dietTags: ['vegan', 'sans_gluten'],
    allergens: [],
    requiredAppliances: ['four'],
    prepTimeMinutes: 15,
    cookTimeMinutes: 25,
    nutrition: { calories: 88, protein: 3, carbs: 12, fat: 3 },
    ingredients: [
      { name: 'quinoa', quantity: 63, unit: 'g', category: 'feculents' },
      { name: 'patate douce', quantity: 0.5, unit: 'piece', category: 'feculents' },
      { name: 'brocoli', quantity: 0.25, unit: 'piece', category: 'legumes' },
      { name: 'pois chiches cuits', quantity: 50, unit: 'g', category: 'legumineuses' },
      { name: "huile d'olive", quantity: 1, unit: 'cas', category: 'matieres_grasses' },
      { name: 'paprika fume', quantity: 1, unit: 'pincee', category: 'epices_condiments' },
    ],
    steps: [
      'Préchauffer le four à 200°C.',
      "Couper la patate douce et le brocoli, les enrober d'huile et de paprika.",
      'Enfourner 25 minutes avec les pois chiches égouttés.',
      'Cuire le quinoa et dresser le bowl avec les légumes rôtis.',
    ],
  },
  {
    id: 'poelee-crevettes-ail',
    name: "Poêlée de crevettes à l'ail",
    servings: 1,
    dietTags: ['omnivore', 'pescatarien', 'sans_gluten'],
    allergens: ['crustaces'],
    requiredAppliances: ['plaque_cuisson'],
    prepTimeMinutes: 10,
    cookTimeMinutes: 5,
    nutrition: { calories: 55, protein: 6.5, carbs: 1, fat: 3 },
    ingredients: [
      { name: 'crevettes decortiquees', quantity: 150, unit: 'g', category: 'viande_poisson' },
      { name: 'ail', quantity: 1, unit: 'gousse', category: 'epices_condiments' },
      { name: 'persil frais', quantity: 10, unit: 'g', category: 'legumes' },
      { name: "huile d'olive", quantity: 1, unit: 'cas', category: 'matieres_grasses' },
      { name: 'piment doux', quantity: 1, unit: 'pincee', category: 'epices_condiments' },
    ],
    steps: [
      "Faire chauffer l'huile d'olive dans une poêle.",
      "Ajouter l'ail émincé et le piment doux.",
      "Saisir les crevettes 3-4 minutes jusqu'à ce qu'elles soient roses.",
      'Parsemer de persil haché et servir immédiatement.',
    ],
  },
  {
    id: 'boeuf-bourguignon',
    name: 'Boeuf bourguignon',
    servings: 1,
    dietTags: ['omnivore', 'sans_gluten'],
    allergens: [],
    requiredAppliances: ['autocuiseur'],
    prepTimeMinutes: 25,
    cookTimeMinutes: 55,
    nutrition: { calories: 80, protein: 6, carbs: 2, fat: 4 },
    ingredients: [
      { name: 'boeuf a braiser', quantity: 200, unit: 'g', category: 'viande_poisson' },
      { name: 'carotte', quantity: 0.7, unit: 'piece', category: 'legumes' },
      { name: 'oignon', quantity: 0.3, unit: 'piece', category: 'legumes' },
      { name: 'champignons de paris', quantity: 40, unit: 'g', category: 'legumes' },
      { name: 'vin rouge', quantity: 80, unit: 'ml', category: 'boissons' },
      { name: 'bouquet garni', quantity: 1, unit: 'piece', category: 'epices_condiments' },
    ],
    steps: [
      "Faire revenir la viande coupée en cubes dans l'autocuiseur.",
      'Ajouter l\'oignon et la carotte émincés, puis le vin rouge.',
      "Incorporer le bouquet garni et fermer l'autocuiseur, cuire 45 minutes.",
      'Ajouter les champignons en fin de cuisson et laisser mijoter 10 minutes.',
    ],
  },
  {
    id: 'chili-sin-carne',
    name: 'Chili sin carne',
    servings: 1,
    dietTags: ['vegan', 'sans_gluten'],
    allergens: [],
    requiredAppliances: ['plaque_cuisson'],
    prepTimeMinutes: 15,
    cookTimeMinutes: 20,
    nutrition: { calories: 78, protein: 4, carbs: 10.5, fat: 2 },
    ingredients: [
      { name: 'haricots rouges cuits', quantity: 100, unit: 'g', category: 'legumineuses' },
      { name: 'mais', quantity: 50, unit: 'g', category: 'legumes' },
      { name: 'tomate concassee', quantity: 100, unit: 'g', category: 'legumes' },
      { name: 'oignon', quantity: 0.25, unit: 'piece', category: 'legumes' },
      { name: 'poivron rouge', quantity: 0.25, unit: 'piece', category: 'legumes' },
      { name: 'piment en poudre', quantity: 1, unit: 'pincee', category: 'epices_condiments' },
      { name: 'cumin moulu', quantity: 1, unit: 'pincee', category: 'epices_condiments' },
    ],
    steps: [
      "Faire revenir l'oignon et le poivron émincés.",
      'Ajouter la tomate concassée, le piment et le cumin.',
      'Incorporer les haricots rouges et le maïs.',
      'Laisser mijoter 20 minutes à couvert.',
    ],
  },
  {
    id: 'wrap-poulet',
    name: 'Wrap au poulet',
    servings: 1,
    dietTags: ['omnivore'],
    allergens: ['gluten'],
    requiredAppliances: ['plaque_cuisson'],
    prepTimeMinutes: 12,
    cookTimeMinutes: 8,
    nutrition: { calories: 95, protein: 7, carbs: 9, fat: 3 },
    ingredients: [
      { name: 'blanc de poulet', quantity: 100, unit: 'g', category: 'viande_poisson' },
      { name: 'tortilla de ble', quantity: 1, unit: 'piece', category: 'feculents' },
      { name: 'salade verte', quantity: 0.25, unit: 'piece', category: 'legumes' },
      { name: 'tomate', quantity: 0.5, unit: 'piece', category: 'legumes' },
      { name: 'sauce yaourt', quantity: 1, unit: 'cas', category: 'produits_laitiers' },
    ],
    steps: [
      'Cuire le poulet coupé en lanières à la poêle.',
      'Garnir la tortilla de salade, tomate et poulet.',
      'Ajouter la sauce au yaourt.',
      'Rouler le wrap et servir.',
    ],
  },
  {
    id: 'pizza-margherita-maison',
    name: 'Pizza margherita maison',
    servings: 1,
    dietTags: ['vegetarien'],
    allergens: ['gluten', 'lactose'],
    requiredAppliances: ['four'],
    prepTimeMinutes: 33,
    cookTimeMinutes: 12,
    nutrition: { calories: 105, protein: 4, carbs: 13.5, fat: 3.5 },
    ingredients: [
      { name: 'pate a pizza', quantity: 65, unit: 'g', category: 'feculents' },
      { name: 'sauce tomate', quantity: 50, unit: 'g', category: 'epicerie' },
      { name: 'mozzarella', quantity: 50, unit: 'g', category: 'produits_laitiers' },
      { name: 'basilic frais', quantity: 4, unit: 'feuille', category: 'legumes' },
      { name: "huile d'olive", quantity: 0.5, unit: 'cas', category: 'matieres_grasses' },
    ],
    steps: [
      'Préchauffer le four à 240°C.',
      'Étaler la pâte et la napper de sauce tomate.',
      'Répartir la mozzarella en tranches.',
      'Enfourner 12 minutes et garnir de basilic frais à la sortie du four.',
    ],
  },
  {
    id: 'burger-vegetarien-maison',
    name: 'Burger végétarien maison',
    servings: 1,
    dietTags: ['vegetarien'],
    allergens: ['gluten', 'lactose', 'oeufs'],
    requiredAppliances: ['plaque_cuisson'],
    prepTimeMinutes: 27,
    cookTimeMinutes: 8,
    nutrition: { calories: 113, protein: 4.5, carbs: 12, fat: 4.5 },
    ingredients: [
      { name: 'haricots rouges cuits', quantity: 75, unit: 'g', category: 'legumineuses' },
      { name: 'chapelure', quantity: 15, unit: 'g', category: 'epicerie' },
      { name: 'oeuf', quantity: 0.25, unit: 'piece', category: 'produits_laitiers' },
      { name: 'pain a burger', quantity: 1, unit: 'piece', category: 'feculents' },
      { name: 'cheddar', quantity: 1, unit: 'tranche', category: 'produits_laitiers' },
      { name: 'salade verte', quantity: 0.25, unit: 'piece', category: 'legumes' },
    ],
    steps: [
      "Écraser les haricots rouges et mélanger avec la chapelure et l'oeuf.",
      'Façonner un steak et le cuire à la poêle 4 minutes par face.',
      'Faire fondre le cheddar sur le steak.',
      'Garnir le pain de salade, du steak et refermer.',
    ],
  },
  {
    id: 'soupe-miso-tofu',
    name: 'Soupe miso au tofu',
    servings: 1,
    dietTags: ['vegan'],
    allergens: ['soja'],
    requiredAppliances: ['plaque_cuisson'],
    prepTimeMinutes: 7,
    cookTimeMinutes: 8,
    nutrition: { calories: 28, protein: 2, carbs: 2, fat: 1 },
    ingredients: [
      { name: 'pate miso', quantity: 1, unit: 'cas', category: 'epicerie' },
      { name: 'tofu soyeux', quantity: 50, unit: 'g', category: 'legumineuses' },
      { name: 'algues wakame', quantity: 3, unit: 'g', category: 'epicerie' },
      { name: 'oignon nouveau', quantity: 0.5, unit: 'piece', category: 'legumes' },
      { name: 'eau', quantity: 250, unit: 'ml', category: 'boissons' },
    ],
    steps: [
      'Faire chauffer l\'eau sans la faire bouillir vivement.',
      'Délayer la pâte miso dans un peu d\'eau chaude puis l\'incorporer.',
      'Ajouter le tofu coupé en cubes et les algues réhydratées.',
      'Garnir d\'oignon nouveau émincé avant de servir.',
    ],
  },
  {
    id: 'riz-saute-legumes',
    name: 'Riz sauté aux légumes',
    servings: 1,
    dietTags: ['vegan', 'sans_gluten'],
    allergens: ['soja'],
    requiredAppliances: ['plaque_cuisson'],
    prepTimeMinutes: 10,
    cookTimeMinutes: 15,
    nutrition: { calories: 80, protein: 2, carbs: 14, fat: 2 },
    ingredients: [
      { name: 'riz cuit refroidi', quantity: 125, unit: 'g', category: 'feculents' },
      { name: 'carotte', quantity: 0.5, unit: 'piece', category: 'legumes' },
      { name: 'petits pois', quantity: 38, unit: 'g', category: 'legumes' },
      { name: 'oignon nouveau', quantity: 1, unit: 'piece', category: 'legumes' },
      { name: 'sauce soja', quantity: 1, unit: 'cas', category: 'epicerie' },
      { name: 'huile de sesame', quantity: 0.5, unit: 'cas', category: 'matieres_grasses' },
    ],
    steps: [
      'Faire chauffer l\'huile de sésame dans une poêle.',
      'Faire sauter la carotte en dés et les petits pois.',
      "Ajouter le riz froid et bien l'émietter à la spatule.",
      "Arroser de sauce soja et parsemer d'oignon nouveau.",
    ],
  },
  {
    id: 'pancakes-banane',
    name: 'Pancakes à la banane',
    servings: 1,
    dietTags: ['vegetarien'],
    allergens: ['gluten', 'lactose', 'oeufs'],
    requiredAppliances: ['robot', 'plaque_cuisson'],
    prepTimeMinutes: 10,
    cookTimeMinutes: 10,
    nutrition: { calories: 78, protein: 2, carbs: 12, fat: 2 },
    ingredients: [
      { name: 'farine de ble', quantity: 50, unit: 'g', category: 'feculents' },
      { name: 'banane', quantity: 0.5, unit: 'piece', category: 'fruits' },
      { name: 'lait', quantity: 63, unit: 'ml', category: 'produits_laitiers' },
      { name: 'oeuf', quantity: 0.5, unit: 'piece', category: 'produits_laitiers' },
      { name: 'levure chimique', quantity: 1, unit: 'pincee', category: 'epicerie' },
      { name: 'beurre', quantity: 5, unit: 'g', category: 'produits_laitiers' },
    ],
    steps: [
      'Mixer la banane avec le lait et l\'oeuf au robot.',
      'Ajouter la farine et la levure, mélanger jusqu\'à obtenir une pâte lisse.',
      'Faire cuire des petites louches de pâte dans une poêle beurrée.',
      "Retourner dès l'apparition de bulles et cuire l'autre face.",
    ],
  },
  {
    id: 'granola-maison',
    name: 'Granola maison',
    servings: 1,
    dietTags: ['vegetarien'],
    allergens: ['fruits_a_coque'],
    requiredAppliances: ['four'],
    prepTimeMinutes: 10,
    cookTimeMinutes: 25,
    nutrition: { calories: 28, protein: 1, carbs: 3.5, fat: 1 },
    ingredients: [
      { name: "flocons d'avoine", quantity: 38, unit: 'g', category: 'feculents' },
      { name: 'amandes effilees', quantity: 10, unit: 'g', category: 'epicerie' },
      { name: 'noix de cajou', quantity: 8, unit: 'g', category: 'epicerie' },
      { name: 'miel', quantity: 10, unit: 'g', category: 'epicerie' },
      { name: 'huile de coco', quantity: 6, unit: 'g', category: 'matieres_grasses' },
    ],
    steps: [
      'Préchauffer le four à 160°C.',
      'Mélanger les flocons d\'avoine avec les fruits à coque.',
      "Ajouter le miel et l'huile de coco fondue, bien enrober.",
      'Étaler sur une plaque et enfourner 25 minutes en remuant à mi-cuisson.',
    ],
  },
  {
    id: 'yaourt-grec-miel-fruits',
    name: 'Yaourt grec au miel et fruits',
    servings: 1,
    dietTags: ['vegetarien', 'sans_gluten'],
    allergens: ['lactose'],
    requiredAppliances: [],
    prepTimeMinutes: 5,
    cookTimeMinutes: 0,
    nutrition: { calories: 110, protein: 6, carbs: 13, fat: 4 },
    ingredients: [
      { name: 'yaourt grec', quantity: 150, unit: 'g', category: 'produits_laitiers' },
      { name: 'miel', quantity: 1, unit: 'cas', category: 'epicerie' },
      { name: 'fruits rouges', quantity: 75, unit: 'g', category: 'fruits' },
    ],
    steps: [
      'Répartir le yaourt grec dans un bol.',
      'Ajouter les fruits rouges frais.',
      'Arroser de miel avant de servir.',
    ],
  },
  {
    id: 'dahl-lentilles-corail',
    name: 'Dahl de lentilles corail',
    servings: 1,
    dietTags: ['vegan', 'sans_gluten'],
    allergens: [],
    requiredAppliances: ['autocuiseur'],
    prepTimeMinutes: 15,
    cookTimeMinutes: 10,
    nutrition: { calories: 73, protein: 3.5, carbs: 10, fat: 2 },
    ingredients: [
      { name: 'lentilles corail', quantity: 75, unit: 'g', category: 'legumineuses' },
      { name: 'lait de coco', quantity: 75, unit: 'ml', category: 'epicerie' },
      { name: 'oignon', quantity: 0.25, unit: 'piece', category: 'legumes' },
      { name: 'curcuma moulu', quantity: 1, unit: 'pincee', category: 'epices_condiments' },
      { name: 'gingembre frais', quantity: 1, unit: 'morceau', category: 'epices_condiments' },
      { name: 'ail', quantity: 0.5, unit: 'gousse', category: 'epices_condiments' },
    ],
    steps: [
      "Faire revenir l'oignon, l'ail et le gingembre dans l'autocuiseur.",
      'Ajouter les lentilles rincées, le curcuma et le lait de coco.',
      "Fermer l'autocuiseur et cuire 10 minutes sous pression.",
      'Laisser dépressuriser et rectifier l\'assaisonnement avant de servir.',
    ],
  },
  {
    id: 'poisson-pane-au-four',
    name: 'Poisson pané au four',
    servings: 1,
    dietTags: ['omnivore', 'pescatarien'],
    allergens: ['poisson', 'gluten'],
    requiredAppliances: ['four'],
    prepTimeMinutes: 15,
    cookTimeMinutes: 20,
    nutrition: { calories: 90, protein: 7.5, carbs: 7, fat: 3.5 },
    ingredients: [
      { name: 'filet de cabillaud', quantity: 150, unit: 'g', category: 'viande_poisson' },
      { name: 'chapelure', quantity: 25, unit: 'g', category: 'epicerie' },
      { name: 'farine de ble', quantity: 13, unit: 'g', category: 'feculents' },
      { name: 'oeuf', quantity: 0.5, unit: 'piece', category: 'produits_laitiers' },
      { name: 'citron', quantity: 0.25, unit: 'piece', category: 'fruits' },
    ],
    steps: [
      'Préchauffer le four à 200°C.',
      'Couper le poisson en portions et le fariner.',
      "Tremper dans l'oeuf battu puis enrober de chapelure.",
      'Disposer sur une plaque et enfourner 20 minutes jusqu\'à coloration dorée.',
    ],
  },
  {
    id: 'curry-poulet-lait-coco',
    name: 'Curry de poulet au lait de coco',
    servings: 1,
    dietTags: ['omnivore', 'sans_gluten', 'sans_lactose'],
    allergens: [],
    requiredAppliances: ['plaque_cuisson'],
    prepTimeMinutes: 15,
    cookTimeMinutes: 20,
    nutrition: { calories: 420, protein: 28, carbs: 38, fat: 18 },
    ingredients: [
      { name: 'blanc de poulet', quantity: 120, unit: 'g', category: 'viande_poisson' },
      { name: 'lait de coco', quantity: 200, unit: 'ml', category: 'epicerie' },
      { name: 'pate de curry rouge', quantity: 1, unit: 'cas', category: 'epices_condiments' },
      { name: 'poivron rouge', quantity: 0.5, unit: 'piece', category: 'legumes' },
      { name: 'oignon', quantity: 0.25, unit: 'piece', category: 'legumes' },
      { name: 'riz basmati', quantity: 75, unit: 'g', category: 'feculents' },
    ],
    steps: [
      "Émincer l'oignon et le poivron.",
      'Faire revenir le poulet coupé en morceaux dans une poêle.',
      "Ajouter la pâte de curry, l'oignon et le poivron, cuire 3 minutes.",
      'Verser le lait de coco et laisser mijoter 12 minutes.',
      'Servir avec le riz basmati cuit à part.',
    ],
  },
  {
    id: 'salade-quinoa-pois-chiches-avocat',
    name: 'Salade de quinoa, pois chiches et avocat',
    servings: 1,
    dietTags: ['vegan', 'sans_gluten', 'sans_lactose'],
    allergens: [],
    requiredAppliances: [],
    prepTimeMinutes: 15,
    cookTimeMinutes: 0,
    nutrition: { calories: 380, protein: 11, carbs: 45, fat: 16 },
    ingredients: [
      { name: 'quinoa', quantity: 60, unit: 'g', category: 'feculents' },
      { name: 'pois chiches cuits', quantity: 80, unit: 'g', category: 'legumineuses' },
      { name: 'avocat', quantity: 0.5, unit: 'piece', category: 'fruits' },
      { name: 'tomate', quantity: 0.5, unit: 'piece', category: 'legumes' },
      { name: 'citron', quantity: 0.25, unit: 'piece', category: 'fruits' },
      { name: "huile d'olive", quantity: 1, unit: 'cas', category: 'matieres_grasses' },
    ],
    steps: [
      'Cuire le quinoa selon les instructions du paquet et le laisser refroidir.',
      'Couper la tomate et l\'avocat en dés.',
      'Mélanger le quinoa, les pois chiches égouttés, la tomate et l\'avocat.',
      "Arroser de jus de citron et d'huile d'olive avant de servir.",
    ],
  },
  {
    id: 'buddha-bowl-tofu-riz-complet',
    name: 'Buddha bowl tofu et riz complet',
    servings: 1,
    dietTags: ['vegan', 'sans_gluten', 'sans_lactose'],
    allergens: ['soja'],
    requiredAppliances: ['plaque_cuisson'],
    prepTimeMinutes: 15,
    cookTimeMinutes: 15,
    nutrition: { calories: 400, protein: 18, carbs: 50, fat: 14 },
    ingredients: [
      { name: 'tofu ferme', quantity: 100, unit: 'g', category: 'legumineuses' },
      { name: 'riz complet', quantity: 80, unit: 'g', category: 'feculents' },
      { name: 'carotte', quantity: 0.5, unit: 'piece', category: 'legumes' },
      { name: 'edamame', quantity: 50, unit: 'g', category: 'legumineuses' },
      { name: 'sauce soja', quantity: 1, unit: 'cas', category: 'epicerie' },
      { name: 'graines de sesame', quantity: 1, unit: 'cac', category: 'epicerie' },
    ],
    steps: [
      'Cuire le riz complet selon les instructions du paquet.',
      'Couper le tofu en cubes et le faire dorer à la poêle.',
      'Râper la carotte et faire cuire les edamame quelques minutes.',
      'Dresser le bowl avec le riz, le tofu, la carotte et les edamame, arroser de sauce soja et parsemer de graines de sésame.',
    ],
  },
  {
    id: 'tartare-saumon-avocat',
    name: "Tartare de saumon à l'avocat",
    servings: 1,
    dietTags: ['omnivore', 'pescatarien', 'sans_gluten', 'sans_lactose'],
    allergens: ['poisson', 'soja'],
    requiredAppliances: [],
    prepTimeMinutes: 15,
    cookTimeMinutes: 0,
    nutrition: { calories: 320, protein: 22, carbs: 6, fat: 22 },
    ingredients: [
      { name: 'pave de saumon', quantity: 120, unit: 'g', category: 'viande_poisson' },
      { name: 'avocat', quantity: 0.5, unit: 'piece', category: 'fruits' },
      { name: 'citron vert', quantity: 0.5, unit: 'piece', category: 'fruits' },
      { name: 'sauce soja', quantity: 1, unit: 'cas', category: 'epicerie' },
      { name: 'oignon nouveau', quantity: 0.5, unit: 'piece', category: 'legumes' },
    ],
    steps: [
      'Couper le saumon frais et l\'avocat en petits dés.',
      "Mélanger délicatement avec le jus de citron vert et la sauce soja.",
      'Parsemer d\'oignon nouveau émincé.',
      'Réserver au frais 10 minutes avant de servir.',
    ],
  },
  {
    id: 'pancakes-vegan-banane',
    name: 'Pancakes vegan à la banane',
    servings: 1,
    dietTags: ['vegan', 'sans_lactose'],
    allergens: ['gluten'],
    requiredAppliances: ['plaque_cuisson'],
    prepTimeMinutes: 10,
    cookTimeMinutes: 10,
    nutrition: { calories: 250, protein: 5, carbs: 40, fat: 7 },
    ingredients: [
      { name: 'farine de ble', quantity: 60, unit: 'g', category: 'feculents' },
      { name: 'banane', quantity: 0.5, unit: 'piece', category: 'fruits' },
      { name: "lait d'amande", quantity: 80, unit: 'ml', category: 'boissons' },
      { name: 'levure chimique', quantity: 1, unit: 'pincee', category: 'epicerie' },
      { name: 'huile de coco', quantity: 1, unit: 'cas', category: 'matieres_grasses' },
    ],
    steps: [
      "Écraser la banane et la mélanger avec le lait d'amande.",
      'Ajouter la farine et la levure, fouetter jusqu\'à obtenir une pâte lisse.',
      'Faire cuire des petites louches de pâte dans une poêle huilée.',
      "Retourner dès l'apparition de bulles et cuire l'autre face.",
    ],
  },
  {
    id: 'curry-lentilles-epinards',
    name: 'Curry de lentilles et épinards',
    servings: 1,
    dietTags: ['vegan', 'sans_gluten', 'sans_lactose'],
    allergens: [],
    requiredAppliances: ['plaque_cuisson'],
    prepTimeMinutes: 10,
    cookTimeMinutes: 20,
    nutrition: { calories: 310, protein: 14, carbs: 38, fat: 10 },
    ingredients: [
      { name: 'lentilles corail', quantity: 80, unit: 'g', category: 'legumineuses' },
      { name: 'epinards frais', quantity: 80, unit: 'g', category: 'legumes' },
      { name: 'lait de coco', quantity: 100, unit: 'ml', category: 'epicerie' },
      { name: 'curcuma moulu', quantity: 1, unit: 'pincee', category: 'epices_condiments' },
      { name: 'ail', quantity: 0.5, unit: 'gousse', category: 'epices_condiments' },
      { name: 'oignon', quantity: 0.25, unit: 'piece', category: 'legumes' },
    ],
    steps: [
      "Faire revenir l'oignon et l'ail émincés.",
      'Ajouter les lentilles rincées, le curcuma et le lait de coco.',
      'Laisser mijoter 15 minutes.',
      'Incorporer les épinards et laisser fondre 5 minutes avant de servir.',
    ],
  },
  {
    id: 'poke-bowl-thon',
    name: 'Poke bowl au thon',
    servings: 1,
    dietTags: ['omnivore', 'pescatarien', 'sans_gluten', 'sans_lactose'],
    allergens: ['poisson', 'soja'],
    requiredAppliances: [],
    prepTimeMinutes: 15,
    cookTimeMinutes: 0,
    nutrition: { calories: 410, protein: 28, carbs: 45, fat: 14 },
    ingredients: [
      { name: 'thon steak', quantity: 120, unit: 'g', category: 'viande_poisson' },
      { name: 'riz vinaigre', quantity: 100, unit: 'g', category: 'feculents' },
      { name: 'edamame', quantity: 50, unit: 'g', category: 'legumineuses' },
      { name: 'concombre', quantity: 0.5, unit: 'piece', category: 'legumes' },
      { name: 'avocat', quantity: 0.5, unit: 'piece', category: 'fruits' },
      { name: 'sauce soja', quantity: 1, unit: 'cas', category: 'epicerie' },
    ],
    steps: [
      'Couper le thon frais et le concombre en dés.',
      'Cuire le riz et le laisser refroidir avec un filet de vinaigre.',
      'Dresser le bowl avec le riz, le thon, le concombre, les edamame et l\'avocat.',
      'Arroser de sauce soja avant de servir.',
    ],
  },
  {
    id: 'galettes-pois-chiches-sans-gluten',
    name: 'Galettes de pois chiches sans gluten',
    servings: 1,
    dietTags: ['vegan', 'sans_gluten', 'sans_lactose'],
    allergens: [],
    requiredAppliances: ['plaque_cuisson'],
    prepTimeMinutes: 15,
    cookTimeMinutes: 10,
    nutrition: { calories: 280, protein: 12, carbs: 36, fat: 9 },
    ingredients: [
      { name: 'pois chiches cuits', quantity: 150, unit: 'g', category: 'legumineuses' },
      { name: 'farine de pois chiche', quantity: 30, unit: 'g', category: 'feculents' },
      { name: 'oignon', quantity: 0.25, unit: 'piece', category: 'legumes' },
      { name: 'persil frais', quantity: 10, unit: 'g', category: 'legumes' },
      { name: 'cumin moulu', quantity: 1, unit: 'pincee', category: 'epices_condiments' },
      { name: "huile d'olive", quantity: 1, unit: 'cas', category: 'matieres_grasses' },
    ],
    steps: [
      'Écraser les pois chiches avec l\'oignon et le persil.',
      'Incorporer la farine de pois chiche et le cumin.',
      'Façonner des petites galettes.',
      'Cuire à la poêle dans l\'huile d\'olive 5 minutes par face.',
    ],
  },
  {
    id: 'veloute-potimarron',
    name: 'Velouté de potimarron',
    servings: 1,
    dietTags: ['vegan', 'sans_gluten', 'sans_lactose'],
    allergens: [],
    requiredAppliances: ['plaque_cuisson', 'blender'],
    prepTimeMinutes: 10,
    cookTimeMinutes: 25,
    nutrition: { calories: 180, protein: 4, carbs: 24, fat: 7 },
    ingredients: [
      { name: 'potimarron', quantity: 250, unit: 'g', category: 'legumes' },
      { name: 'bouillon de legumes', quantity: 300, unit: 'ml', category: 'epicerie' },
      { name: 'oignon', quantity: 0.25, unit: 'piece', category: 'legumes' },
      { name: 'lait de coco', quantity: 50, unit: 'ml', category: 'epicerie' },
      { name: 'muscade', quantity: 1, unit: 'pincee', category: 'epices_condiments' },
    ],
    steps: [
      'Couper le potimarron en cubes sans le peler.',
      "Faire revenir l'oignon puis ajouter le potimarron et le bouillon.",
      'Laisser mijoter 20 minutes jusqu\'à ce que le potimarron soit tendre.',
      'Mixer avec le lait de coco et la muscade jusqu\'à obtenir une texture lisse.',
    ],
  },
  {
    id: 'brochettes-boeuf-marine-four',
    name: 'Brochettes de boeuf marinées au four',
    servings: 1,
    dietTags: ['omnivore', 'sans_gluten', 'sans_lactose'],
    allergens: [],
    requiredAppliances: ['four'],
    prepTimeMinutes: 20,
    cookTimeMinutes: 12,
    nutrition: { calories: 320, protein: 26, carbs: 8, fat: 20 },
    ingredients: [
      { name: 'boeuf a braiser', quantity: 150, unit: 'g', category: 'viande_poisson' },
      { name: 'poivron rouge', quantity: 0.5, unit: 'piece', category: 'legumes' },
      { name: 'oignon rouge', quantity: 0.25, unit: 'piece', category: 'legumes' },
      { name: "huile d'olive", quantity: 1, unit: 'cas', category: 'matieres_grasses' },
      { name: 'paprika fume', quantity: 1, unit: 'pincee', category: 'epices_condiments' },
    ],
    steps: [
      "Couper le boeuf et les légumes en cubes réguliers.",
      "Mariner la viande avec l'huile d'olive et le paprika fumé 15 minutes.",
      'Enfiler la viande et les légumes sur une brochette en alternant.',
      'Enfourner 12 minutes à 220°C en retournant à mi-cuisson.',
    ],
  },
];
